#!/bin/sh

config=/bin/config

/sbin/rmmod ip_nat_dnisip.ko > /dev/null
/sbin/rmmod ip_conntrack_dnisip.ko > /dev/null

if [ "$($config get wan_endis_sipalg)" != "1" ]; then
	/sbin/insmod /lib/modules/2.6.15/ip_conntrack_dnisip.ko
	/sbin/insmod /lib/modules/2.6.15/ip_nat_dnisip.ko
fi
