#!/bin/sh

RAM_ROOT=/tmp/root

ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
libs() { ldd $* | awk '{print $3}'; }

install_file() { # <file> [ <file> ... ]
	for file in "$@"; do
		dest="$RAM_ROOT/$file"
		[ -f $file -a ! -f $dest ] && {
			dir="$(dirname $dest)"
			mkdir -p "$dir"
			cp -af $file $dest
		}
	done
}

install_bin() { # <file> [ <symlink> ... ]
	src=$1
	files=$1
	[ -x "$src" ] && files="$src $(libs $src)"
	install_file $files
	shift
	for link in "$@"; do {
		dest="$RAM_ROOT/$link"
		dir="$(dirname $dest)"
		mkdir -p "$dir"
		[ -f "$dest" ] || ln -s $src $dest
	}; done
}

pivot() { # <new_root> <old_root>
	mount | grep "on $1 type" 2>&- 1>&- || mount -o bind $1 $1 && \
	mkdir -p $1$2 $1/proc $1/dev $1/tmp && \
	mount -o move /dev $1/dev && \
	mount -o move /proc $1/proc && \
	pivot_root $1 $1$2 || {
        	umount $1 $1
		return 1
	}
	mount -o move $2/tmp /tmp
	#mount -o move $2/jffs /jffs 2>&-
	return 0
}

run_ramfs() { # <command> [...]
	killall smbd
	dd if=/dev/zero of=/tmp/tmp11 bs=10M count=1
	rm /tmp/tmp11 -rf
	install_bin /bin/busybox /bin/ash /bin/sh /bin/mount /bin/umount /sbin/pivot_root /sbin/reboot /bin/sync
	install_bin /sbin/mtd
	install_bin /usr/sbin/net-cgi
	install_file /usr/www/languages-en.js
	install_file /usr/www/liteblue.gif /usr/www/style/form.css /usr/www/pls_wait.html /usr/www/help.css /usr/www/help.htm /usr/www/upload.gif /usr/www/funcs.js /usr/www/UPG_process.htm /usr/www/spacer.gif /usr/www/AUTO_upgrade_process.htm /usr/www/upg_get_status.htm
	install_file /etc/resolv.conf
	install_file /lib/libcrypt.so.0 /lib/libgcc_s.so.1 /lib/libc.so.0 /lib/ld-uClibc.so.0 /lib/libcrypt-0.9.30.3.so /lib/libuClibc-0.9.30.3.so /lib/ld-uClibc-0.9.30.3.so /lib/libpthread-0.9.30.3.so /lib/libpthread.so.0 /lib/libm.so.0 /lib/libm-0.9.30.3.so /usr/lib/libconfig.so
	mv $RAM_ROOT/usr/www $RAM_ROOT/www
	
	pivot $RAM_ROOT /mnt || {
		echo "Failed to switch over to ramfs. Please reboot."
		exit 1
	}


	# spawn a new shell from ramdisk to reduce the probability of cache issues
	exec /bin/busybox ash -c "$*"

}

run_ramfs

