#!/bin/sh

### Button status defination
FREE=0	# Button is pop up
PUSH=1	# Button is pressed
HOLD=2	# Button is pressed and hold on a moment

### Free button pressed state
free_pushbut=10
free_wifibut=20
free_resetbut=30

### Tool
CONFIG=/bin/config

file=/proc/simple_config/button_state
buttonstate=
pushbutton=${FREE}
wifibutton=${FREE}
resetbutton=${FREE}

#initialization buttons' states
echo 10 > ${buttonstate}
echo 20 > ${buttonstate}
echo 30 > ${buttonstate}

while [ 1 ]
do
	factory=`config get factory_mode`
	if [ "x$factory" = "x1" ];then
		/bin/sleep 1
		echo ${free_resetbut} > ${file}
		echo ${free_wifibut} > ${file}
		echo ${free_pushbut} > ${file}
		continue
	fi
	#get states of buttons
	buttonstate=$(/bin/cat ${file})
	pushbutton=$(/bin/echo ${buttonstate} | cut -c 2)
	wifibutton=$(/bin/echo ${buttonstate} | cut -c 4)
	resetbutton=$(/bin/echo ${buttonstate} | cut -c 6)

	if [ ${PUSH} -eq ${pushbutton} ]; then
		if [ "$(${CONFIG} get endis_wl_radio)" = "1" -a "$(${CONFIG} get endis_wl_wps)" = "0" ] ||
		[ "$(${CONFIG} get endis_wla_radio)" = "1" -a "$(${CONFIG} get endis_wla_wps)" = "0" ]
		then
			# WPS is disabled, WPS LED will be controlled by kernel to blinking
			if [ "$(${CONFIG} get wl_sectype)" != "1" -o "$(${CONFIG} get wla_sectype)" != "1" ]; then
				echo 1 > /proc/simple_config/diswps
			else
				echo 2 > /proc/simple_config/diswps
			fi
		elif [ "$(${CONFIG} get endis_wl_radio)" != "0" -o "$(${CONFIG} get endis_wla_radio)" != "0" ]; then
			# WPS is enabled
			echo 0 > /proc/simple_config/diswps

			wlan wps --pbc_start
			echo "start" > /tmp/wps_process_state
		fi
		echo ${free_pushbut} > ${file}
	fi

	if [ ${PUSH} -eq ${wifibutton} ]; then
		wlan toggle
		echo ${free_wifibut} > ${file}
	fi

	if [ ${PUSH} -eq ${resetbutton} ]; then
		/sbin/reboot
		echo ${free_resetbut} > ${file}
	elif [ ${HOLD} -eq ${resetbutton} ]; then
		/bin/config default
		/sbin/reboot
		echo ${free_resetbut} > ${file}
	fi

	/bin/sleep 1
done


