#!/bin/sh

CONFIG="/bin/config"

/sbin/rmmod nf_nat_dnisip.ko > /dev/null
/sbin/rmmod nf_conntrack_dnisip.ko > /dev/null

if [ "$($CONFIG get wan_endis_sipalg)" != "1" ]; then
	/sbin/insmod nf_conntrack_dnisip.ko sip_direct_media=0
	/sbin/insmod nf_nat_dnisip.ko
fi
