#!/bin/sh /etc/rc.common
START=81

CONFIG=/bin/config
gui_region=$($CONFIG get GUI_Region)
firmware_region=`cat /tmp/firmware_region | awk '{print $1}'`

is_interface_exist()
{
	brctl show | awk '/$(IPTV_BRIDGE_NAME)/, /^$/' | grep $1 1>/dev/null

        if [ $? = 0 ]; then
                echo "1"
        else
                echo "0"
        fi

}

restart_wireless(){
	ifconfig $1 down
	sleep 7
	ifconfig $1 up
}

config_wireless_iptv()
{
	wl_1st_iptv="$($CONFIG get wan_brig_ssid1)"
	wl_2nd_iptv="$($CONFIG get wan_brig_ssid2)"
	wl_guest_iptv1="$($CONFIG get wan_brig_guest_ssid1)"
	wl_guest_iptv2="$($CONFIG get wan_brig_guest_ssid2)"
	wlg_guest_on="$($CONFIG get wlg1_endis_guestNet)"
	wla_guest_on="$($CONFIG get wla1_endis_guestNet)"

        #check if any wireless interface will be set as IPTV port
        if [ "$wl_1st_iptv" = "1" -o "$wl_2nd_iptv" = "1" -o "$wl_guest_iptv1" = "1" -o "$wl_guest_iptv2" = "1" ]; then
                if [ `is_interface_exist "$(IPTV_BRIDGE_NAME)"` = "0" ]; then
                        brctl addbr $(IPTV_BRIDGE_NAME)
                        brctl addif $(IPTV_BRIDGE_NAME) $(WAN_NAME)
                        ifconfig $(IPTV_BRIDGE_NAME) up
                fi
        fi

        #if ath0 is to be set as IPTV port and ath0 has not benn added to $(IPTV_BRIDGE_NAME), then add ath0 to $(IPTV_BRIDGE_NAME)
        if [ "$wl_1st_iptv" = "1" ] && [ `is_interface_exist "$(WLAN_NG_NAME)"` = "0" ]; then
                brctl delif $(BRIDGE_NAME) $(WLAN_NG_NAME)
                brctl addif $(IPTV_BRIDGE_NAME) $(WLAN_NG_NAME)
        elif [ "$wl_1st_iptv" = "0" ] && [ `is_interface_exist "$(WLAN_NG_NAME)"` = "1" ]; then
                brctl delif $(IPTV_BRIDGE_NAME) $(WLAN_NG_NAME)
                brctl addif $(BRIDGE_NAME) $(WLAN_NG_NAME)
        fi

        if [ "$wl_2nd_iptv" = "1" ] && [ `is_interface_exist "$(WLAN_A_NAME)"` = "0" ]; then
                brctl delif $(BRIDGE_NAME) $(WLAN_A_NAME)
                brctl addif $(IPTV_BRIDGE_NAME) $(WLAN_A_NAME)
        elif [ "$wl_2nd_iptv" = "0" ] && [ `is_interface_exist "$(WLAN_A_NAME)"` = "1" ]; then
                brctl delif $(IPTV_BRIDGE_NAME) $(WLAN_A_NAME)
                brctl addif $(BRIDGE_NAME) $(WLAN_A_NAME)
        fi

	#if we only enable 5G Guest Network, now ath2 is 5G Gusest Network Interface.
	if [ "$wlg_guest_on" = "0" -a "$wla_guest_on" = "1" ]; then
		if [ "$wl_guest_iptv2" = "1" ] && [ `is_interface_exist "$(WLAN_NAME_2)"` = "0" ]; then
			brctl delif $(BRIDGE_NAME) $(WLAN_NAME_2)
			brctl addif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_2)
		elif [ "$wl_guest_iptv2" = "0" ] && [ `is_interface_exist "$(WLAN_NAME_2)"` = "1" ]; then
			brctl delif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_2)
			brctl addif $(BRIDGE_NAME) $(WLAN_NAME_2)
		fi
	else
		if [ "$wl_guest_iptv1" = "1" ] && [ `is_interface_exist "$(WLAN_NAME_2)"` = "0" ]; then
			brctl delif $(BRIDGE_NAME) $(WLAN_NAME_2)
			brctl addif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_2)
		elif [ "$wl_guest_iptv1" = "0" ] && [ `is_interface_exist "$(WLAN_NAME_2)"` = "1" ]; then
			brctl delif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_2)
			brctl addif $(BRIDGE_NAME) $(WLAN_NAME_2)
		fi

		if [ "$wl_guest_iptv2" = "1" ] && [ `is_interface_exist "$(WLAN_NAME_3)"` = "0" ]; then
			brctl delif $(BRIDGE_NAME) $(WLAN_NAME_3)
			brctl addif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_3)
		elif [ "$wl_guest_iptv2" = "0" ] && [ `is_interface_exist "$(WLAN_NAME_3)"` = "1" ]; then
			brctl delif $(IPTV_BRIDGE_NAME) $(WLAN_NAME_3)
			brctl addif $(BRIDGE_NAME) $(WLAN_NAME_3)
		fi
	fi

	if [ "$wl_1st_iptv" = "0" -a "$wl_2nd_iptv" = "0" -a "$wl_guest_iptv1" = "0" -a "$wl_guest_iptv2" = "0" ] &&
	   [ `is_interface_exist "$(IPTV_BRIDGE_NAME)"` = "1" ]; then
		ifconfig $(IPTV_BRIDGE_NAME) down
		brctl delbr $(IPTV_BRIDGE_NAME)
		ifconfig $(WAN_NAME) up
	fi
}

config_wire_port(){
	vlan-set $($CONFIG get iptv_mask) 1>/tmp/vlan-set-result
	dni_eth --switch-lan-phy 9 --switch-lan-mask $($CONFIG get iptv_mask_change) 
	#After restart the changed port,reset the iptv_mask_change to '0'
	$CONFIG set iptv_mask_change=0
}

if [ "$firmware_region" = "" ] || [ "$firmware_region" = "WW" ]; then
	if [ "$gui_region" = "Russian" ]; then
		config_wire_port
		config_wireless_iptv
	else
		vlan-set 0 1>/tmp/vlan-set-result
	fi
elif [ "$firmware_region" = "RU" ]; then
	config_wire_port
	config_wireless_iptv
else
	vlan-set 0 1>/tmp/vlan-set-result
fi


